# Diccionario completo de números y sus significados
numeros_significados = {
    "01": ["caballo", "sol", "tintero", "camello", "pescado chico", "fiebre alta"],
    "02": ["mariposa", "hombre", "cafetera", "caracol"],
    "03": ["marinero", "niño", "viaje", "luna", "taza", "ciempiés", "muerto"],
    "04": ["gato", "soldado", "llave", "vela", "boca", "militar", "pavo real"],
    "05": ["monja", "mar", "candado", "periódico", "fruta", "lombriz", "lengua"],
    "06": ["jicotea", "aereoplano", "carta", "reverbero", "botella", "luna"],
    "07": ["caracol", "sueño", "mierda", "medias", "caballero", "cochino", "culo"],
    "08": ["muerto", "león", "calabaza", "mesa", "tigre"],
    "09": ["elefante", "entierro", "lira", "cubo", "esqueleto", "buey"],
    "10": ["pescado grande", "paseo", "malla", "cazuela", "dinero", "lancha", "miedo"],
    "11": ["gallo", "lluvia", "fosforera", "taller", "fábrica", "caballo", "miami"],
    "12": ["mujer santa", "viaje", "toallas", "cometa", "dama", "perro grande", "ropa"],
    "13": ["pavo real", "niño", "anafe", "souteneur", "elefante"],
    "14": ["gato tigre", "matrimonio", "arreste", "sartén", "cementerio"],
    "15": ["perro", "visita", "cuchara", "gallo", "ratón"],
    "16": [
        "toro",
        "plancha",
        "vestido",
        "incendio pequeño",
        "funerales",
        "avispa",
        "regalo",
    ],
    "17": [
        "luna",
        "mujer buena",
        "hule",
        "camisón",
        "armas",
        "fumar opio",
        "san lázaro",
        "viaje",
    ],
    "18": [
        "pescado chiquito",
        "iglesia",
        "sirena",
        "palma",
        "pescado",
        "gato amarillo",
    ],
    "19": [
        "lombriz",
        "campesino",
        "tropa",
        "mesa grande",
        "armadura",
        "jutía",
        "caída",
    ],
    "20": ["gato fino", "cañón", "camiseta", "frijol", "orinal", "libro", "mujer"],
    "21": ["maja", "reloj de bolsillo", "chaleco", "cotorra", "cigarro", "gallo"],
    "22": ["sapo", "estrella", "lirio", "chimenea", "sol", "jicotea"],
    "23": ["vapor", "submarino", "monte", "escalera", "barco", "águila"],
    "24": ["paloma", "música", "carpintero", "cocina", "pescado grande", "hermano"],
    "25": ["piedra fina", "casa", "sol", "monja", "rana", "ojo", "lágrimas"],
    "26": ["anguila", "calle", "médico", "brillante", "nube de oro"],
    "27": ["avispa", "campana", "cuchara grande", "canario", "baúl", "mono"],
    "28": ["chivo", "bandera", "político", "uvas", "perro chico", "bollo"],
    "29": ["ratón", "nube", "venado", "águila", "carpintero"],
    "30": ["camarón", "arco iris", "almanaque", "buey", "cangrejo", "chivo"],
    "31": ["venado", "escuela", "zapatos", "pato", "diente"],
    "32": ["cochino", "enemigo", "mulo", "demonio", "maja", "dentista"],
    "33": ["tiñosa", "baraja", "santa", "jesucristo", "bofetón", "camarón"],
    "34": ["mono", "familia", "negro", "capataz", "paloma"],
    "35": ["araña", "novia", "bombillos", "mosquito", "mariposa"],
    "36": ["cachimba", "teatro", "bodega", "opio", "coloso", "pajarito"],
    "37": [
        "gallina prieta",
        "gitana",
        "hormiga",
        "carretera",
        "piedra fina",
        "brujería",
    ],
    "38": ["dinero", "macao", "carro", "goleta", "guantes", "barril"],
    "39": ["conejo", "culebra", "rayo", "baile", "tintorero", "ladrón", "pelota"],
    "40": ["cura", "sangre", "bombero", "muchacho maldita", "cantina", "estatua"],
    "41": [
        "lagartija",
        "prisión",
        "pato chico",
        "jubo",
        "capuchino",
        "clarín",
        "plato",
    ],
    "42": ["pato", "país lejano", "carnero", "españa", "abismo", "liga"],
    "43": ["alacrán", "amigo", "vaca", "puerta", "presidiario", "jorobado"],
    "44": ["año del cuero", "infierno", "año malo", "temporal", "tormenta", "plancha"],
    "45": ["tiburón", "presidente", "traje", "tranvía", "escuela", "estrella"],
    "46": ["guagua", "humo", "hambre", "hurón", "baile", "chino"],
    "47": ["pájaro", "mala noticia", "mucha sangre", "escolta", "gallo", "rosa"],
    "48": ["cucaracha", "abanico", "barbería", "cubo", "tiburón"],
    "49": ["borracho", "riqueza", "figurín", "percha", "tesoro", "fantasma", "fogón"],
    "50": ["policía", "alegría", "florero", "alcalde", "pícaro", "árbol"],
    "51": ["soldado", "sed", "oro", "sereno", "anteojos", "presillas", "cumpleaños"],
    "52": ["bicicleta", "coche", "borracho", "abogado", "riña", "libreta"],
    "53": ["luz eléctrica", "prenda", "tragedia", "diamante", "beso", "alguacil"],
    "54": ["flores", "gallina", "blanca", "sueño", "timbre", "cañón", "rosas"],
    "55": ["cangrejo", "baile", "iglesia grande", "los isleños", "caerse", "sellos"],
    "56": [
        "reina escorpión",
        "pato grande",
        "merengue",
        "piedra",
        "cara",
        "dolor de cabeza",
        "nieto",
    ],
    "57": ["cama", "ángeles", "telegrama", "puerta", "san lázaro"],
    "58": ["adulterio", "retrato", "cuchillo", "cangrejo", "ferretero", "batea"],
    "59": ["loco", "fonógrafo", "langosta", "anillo", "araña grande"],
    "60": ["sol oscuro", "huevo", "payaso", "cómico", "tempestad", "ave pequeña"],
    "61": [
        "cañonazo",
        "piedra grande",
        "revolver",
        "boticario",
        "pintor",
        "saco",
        "enfermo",
    ],
    "62": ["matrimonio", "nieve", "lámpara", "visión", "academia", "carretilla"],
    "63": ["asesino", "cuernos", "espada", "bandidos", "caracol", "escalera"],
    "64": ["muerto grande", "tiro de rifle", "maromero", "relajo", "vahos", "fiera"],
    "65": ["cárcel", "comida", "brujo", "pájaro", "coronel", "perro pequeño", "fruta"],
    "66": ["bruja", "platos", "mujer mala", "cama mala", "dientes", "monstruo"],
    "67": ["doctor", "burro", "bandido", "llave", "azul", "muerto"],
    "68": ["fruta madura", "confusión", "oscuro", "fantasma", "pájaro", "escoba"],
    "69": ["traje de fiesta", "guagua", "cargador", "profesión", "ángel guardián"],
    "70": ["mentiroso", "guardia", "colgado", "cazuela", "lira"],
    "71": ["castigo", "religión", "machete", "cántaro", "carro", "veterano"],
    "72": ["corcho", "gancho", "diamante", "banquero", "cigarrillos"],
    "73": ["buey", "trompeta", "lápiz", "fábrica", "dólares", "calavera"],
    "74": ["violín", "oveja", "hospital", "venado", "viento", "candil"],
    "75": ["cura grande", "mejilla", "bruja mala", "maroma", "camisa"],
    "76": ["sueño", "carroza", "candado", "colchón", "mosquito"],
    "77": ["vieja", "escuela grande", "espejo", "hombre grande", "novio"],
    "78": ["cochino pequeño", "yuca", "cúpula", "cerdo", "caña"],
    "79": ["ángel grande", "sillón", "torre", "grifo", "orquídea", "esperanza"],
    "80": ["tabaco", "sueño grande", "dama vieja", "brujo grande"],
    "81": ["chaqueta", "balanza", "guitarra", "estrella"],
    "82": ["araña", "colegio", "jirafa", "palacio", "niña", "cañonera"],
    "83": ["juez", "muela", "paloma grande", "caldero", "víbora"],
    "84": ["tigre", "hospital grande", "monte", "basurero", "montón"],
    "85": ["capitán", "laguna", "reloj", "fotografía", "cañón grande"],
    "86": ["coche grande", "campanilla", "piedra blanca", "rosa grande"],
    "87": ["paloma", "estación de policía", "botella de leche", "madre grande"],
    "88": ["candelabro", "templo", "familia grande", "calavera"],
    "89": ["tarántula", "brujo viejo", "hospital del sol", "árbol grande"],
    "90": ["plato grande", "tigre de fuego", "espada grande", "carro grande"],
    "91": ["elefante grande", "ceremonia", "mercado", "portón"],
    "92": ["buque grande", "teatro grande", "carroza grande", "espejo grande"],
    "93": ["familia pequeña", "nube pequeña", "tiempo malo", "cielo grande"],
    "94": ["sol pequeño", "barril grande", "conejo pequeño", "piedra mala"],
    "95": ["reina del sol", "calavera grande", "mar malo", "puente grande"],
    "96": ["ventana pequeña", "estufa grande", "muro grande", "calavera pequeña"],
    "97": ["puente pequeño", "teatro pequeño", "elefante pequeño", "guerrero"],
    "98": ["monja vieja", "bruja pequeña", "mujer vieja", "religión grande"],
    "99": ["sueño grande", "gallo grande", "fuego grande", "mujer joven"],
}
